### ISSUE TITLE
All VCL content is source.varnish.vcl

### ISSUE THREAD

**Issue by command-tab** [zephirworks/Varnish.tmbundle#1]
After installing the Varnish.tmbundle plugin (and relaunching TextMate for good measure) my .vcl files still don't get proper syntax coloring.  I had a custom theme defined which didn't of course account for this new syntax, but even with a few colors defined, the only part of the file that gets colors is comments.

When I hit Control-Shift-P to get TextMate to tell me what grammar type a given word in a .vcl file is, everything shows up as source.varnish.vcl.  Comments get this, as well as comment.line.vcl.

Am I missing something? Or is something wrong with the syntax definition?  Or something else?

**Comment by robsonpeixoto** [comment]
I tested on textmate 2 and are working very well

**Comment by command-tab** [comment]
Indeed works great with TextMate 2. Thanks!
